### ISSUE TITLE
IP allocator: can allocate network address !

### ISSUE THREAD

**Issue by aaronkaplan** [FunkFeuer/Graz#22]
Something seems to be very wrong if you can allocate the network address: 
In a test (clean DB) I was able to allocate the IP address 193.33.150.0

However, this is the network address of this block:

```
inetnum:        193.33.150.0 - 193.33.151.255
netname:        FFGRAZ-NET
descr:          FunkFeuer Graz - Verein zur Foerderung freier Netze
descr:          Wireless community ad-hoc mesh network
country:        AT
remarks:        ***************************************************************
remarks:        please report abuse incidents (eg network scanning, spam, etc.)
remarks:        ONLY to < abuse@graz.funkfeuer.at >
remarks:        ***************************************************************
```

This can't be!

**Comment by equinox0815** [comment]
I disagree. Assigning this address is totally ok. I wouldn't do it for some reasons but there is nothing really wrong with that.
In my opinion the system shouldn't forbid to assign this adress.

**Comment by aaronkaplan** [comment]
On Mar 16, 2015, at 10:08 PM, equinox0815 notifications@github.com wrote:

> I disagree. Assining this address is totally ok. I wouldn't do it for some reasons but there is nothing really wrong with that.
> In my opinion the system shouldn't forbid to assign this adress.

okay, you guys know better... I would never assign a network address but hey, if you are OK with it, I'll then close this issue.

**Comment by schlatterbeck** [comment]
On Tue, Mar 17, 2015 at 02:49:33AM -0700, AaronK wrote:

> On Mar 16, 2015, at 10:08 PM, equinox0815 notifications@github.com wrote:
> 
> > I disagree. Assining this address is totally ok. I wouldn't do it
> > for some reasons but there is nothing really wrong with that.
> > In my opinion the system shouldn't forbid to assign this adress.
> 
> okay, you guys know better... I would never assign a network address
> but hey, if you are OK with it, I'll then close this issue.

In my opinion this is a policy-decision. You should reserve network
addresses that you don't want to be assigned. And we may see a lot of
assigned network addresses as IPv4 space is exhausted :-)

But I'm not sure that even a broadcast address might be assigned if not
specially reserved, so maybe at least the converter should reserve
these.

## Ralf

Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   http://www.runtux.com
Reichergasse 131, A-3411 Weidling       email: office@runtux.com
allmenda.com member                     email: rsc@allmenda.com

**Comment by equinox0815** [comment]
The thing is that our networks really don't work like classic networks. These consist of LAN segments which have assigned subnets. Each of which have network and broadcast addresses. At least the broadcast address has a special meaning the network address doesn't have any special purpose in the real world - it's just a best practice.
In the context of our netwoks as well as in the context of BGP on the internet the subnet mask is more a way to define ranges of addresses. BGP doesn't tell you how to subnet these ranges. If you for example use the range for point-to-point communication there is no point in leaving out the network address or even the broadcast address of such a block. Often you can not even tell whether an address is i.e. a broadcast adress because you don't know which subnets are used.

**Comment by schlatterbeck** [comment]
On Tue, Mar 17, 2015 at 04:13:43AM -0700, equinox0815 wrote:
[...]

> If you for example
> use the range for point-to-point communication there is no point in
> leaving out the network address or even the broadcast address of such
> a block. Often you can not even tell whether an address is i.e. a
> broadcast adress because you don't know which subnets are used. 

That's why I'd recommend to _explicitly_ reserve these addresses if they
should not be used.

## Ralf

Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   http://www.runtux.com
Reichergasse 131, A-3411 Weidling       email: office@runtux.com
allmenda.com member                     email: rsc@allmenda.com

**Comment by equinox0815** [comment]
Seas,

Am 2015-03-17 um 15:37 schrieb Ralf Schlatterbeck:

> On Tue, Mar 17, 2015 at 04:13:43AM -0700, equinox0815 wrote:
> [...]
> 
> > If you for example
> > use the range for point-to-point communication there is no point in
> > leaving out the network address or even the broadcast address of such
> > a block. Often you can not even tell whether an address is i.e. a
> > broadcast adress because you don't know which subnets are used.
> 
> That's why I'd recommend to _explicitly_ reserve these addresses if they
> should not be used.
> 
> I think you missunderstood me there. I think it is not possible to know
> which addresses are broadcasts so i can't explicitly reserve them. For
> the example from Aaron: we got an /23 assigned by ripe. This means:

Network Address: 193.33.150.0
Braodcast Address: 193.33.151.255

But what if you want to use this range as two /24 ranges, in that case
we would need to reserve 193.33.150.255 and 193.33.151.0 as well. But
what if we later decide to reserve a /27 for our housing somewhere -
then we have again some addresses which should be reserved...

This can go one until nearly all addresses are reserved. Sorry if i say
that this way but i think the whole idea of reserved addresses inside
the database application is extremly stupid to begin with and i always
find it extremly frustrating if some software doesn't let me set things
that i need just because there are some cases where it could go wrong.

I still can reserve those addresses by just assigning them to a special
pseudo node. That way nobody can accidently pick a 'reserved' address
and still leaves me with all possibilities for the future.

regards
 christian

**Comment by aaronkaplan** [comment]
OkaY. Understood and thanks for the comments. 

So we leave that out of the database then. 

---

Mobile

**Comment by schlatterbeck** [comment]
On Tue, Mar 17, 2015 at 09:18:08AM -0700, equinox0815 wrote:

> I still can reserve those addresses by just assigning them to a special
> pseudo node. That way nobody can accidently pick a 'reserved' address
> and still leaves me with all possibilities for the future.

Thats exactly what I meant with my last comment. You make a policy
decision that for a specific network users may assign /32 addresses from
a certain range and that you do _not_ want them to assign a .0 or .255
or something address. Then you explicitly reserve that address from the
given range (by assigning it to an admin) to prevent that. Sorry for
being too terse in my comment.

Ralf

## 

Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   http://www.runtux.com
Reichergasse 131, A-3411 Weidling       email: office@runtux.com
allmenda.com member                     email: rsc@allmenda.com
